# Copyright 2019 Matthew Vernacchia
# Based on https://github.com/squidfunk/mkdocs-material/blob/master/mkdocs.yml

# Project information
site_name: Matt Vernacchia
site_description: A portfolio of my engineering work.
site_author: Matt Vernacchia
site_url: https://mvernacc.github.io/portfolio/

# Repository
repo_name: mvernacc/portfolio
repo_url: https://github.com/mvernacc/portfolio/
edit_uri: ""

# Copyright
copyright: 'Copyright &copy; 2025 Matthew Vernacchia'

# Configuration
theme:
  name: 'material'

extra_css:
  - 'stylesheets/portfolio.css'

# Customization
extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/mvernacc
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/matthew-vernacchia-4848023b/
    - icon: fontawesome/brands/researchgate
      link: https://www.researchgate.net/profile/Matthew_Vernacchia


# Extensions
markdown_extensions:
  - admonition
  - footnotes
  - pymdownx.details
  - toc:
      permalink: true
  - pymdownx.smartsymbols
  - pymdownx.arithmatex
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

extra_javascript:
  - 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML'


# Page tree
nav:
  - Overview: index.md
  - Resume: resume.md
  - Publications: publications.md
  - Engineering Notes: engineering_notes.md
  - Hardware Projects: hardware_projects.md
  - Software Projects: software_projects.md




